# -*- coding: utf-8 -*-
"""ETL_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y55ip79PRl1niKwY273Ft7zo1jIiDJvX
"""

# Install KaggleHub and dependencies
!pip install kagglehub pandas sqlalchemy openpyxl --quiet

import pandas as pd
import sqlite3
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Download dataset folder
dataset_path = kagglehub.dataset_download("raghu07/ipl-data-till-2017")
print("Dataset downloaded to:", dataset_path)

# Define file paths (dataset contains Match.csv, Ball_By_Ball.csv, etc.)
match_fp = dataset_path + "/Match.csv"
ball_fp = dataset_path + "/Ball_By_Ball.csv"
player_fp = dataset_path + "/Player.csv"
team_fp = dataset_path + "/Team.csv"
player_match_fp = dataset_path + "/Player_match.csv"

# Read into pandas
matches = pd.read_csv(match_fp, encoding="latin1")
balls = pd.read_csv(ball_fp, encoding="latin1")
players = pd.read_csv(player_fp, encoding="latin1")
teams = pd.read_csv(team_fp, encoding="latin1")
player_match = pd.read_csv(player_match_fp, encoding="latin1")

print(" Data Loaded")
print("Matches:", matches.shape, " Balls:", balls.shape, " Players:", players.shape)

matches_2017 = matches[matches["Season_Year"] == 2017]
balls_2017 = balls[balls["Season"] == 2017]
player_match_2017 = player_match[player_match["Season_year"] == 2017]

print("Matches 2017:", matches_2017.shape)

# Aggregate runs scored by striker
batsman_runs = balls_2017.groupby("Striker").agg(Runs=('Runs_Scored','sum')).reset_index()

# Join with Player to get names
batsman_runs = batsman_runs.merge(players[['Player_Id','Player_Name']],
                                  left_on="Striker", right_on="Player_Id", how="left")

top_batsmen = batsman_runs[['Player_Name','Runs']].sort_values("Runs", ascending=False).head(10)

print(" Top Batsmen 2017 by Runs:")
print(top_batsmen)

# Drop matches without winners
matches_2017 = matches_2017.dropna(subset=["match_winner"])

# Wins per team
team_wins = matches_2017['match_winner'].value_counts().reset_index()
team_wins.columns = ['Team', 'Wins']

print(" Teams with Most Wins 2017:")
print(team_wins)

# Count awards directly by player name
mvp_awards = matches_2017['ManOfMach'].value_counts().reset_index()
mvp_awards.columns = ['Player_Name','Awards']

# Top MVPs
top_mvps = mvp_awards[['Player_Name','Awards']].sort_values("Awards", ascending=False).head(10)

print(" Top MVPs 2017:")
print(top_mvps)

conn = sqlite3.connect("ipl2017_etl.db")

top_batsmen.to_sql("Top_Batsmen_2017", conn, if_exists="replace", index=False)
team_wins.to_sql("Team_Wins_2017", conn, if_exists="replace", index=False)
top_mvps.to_sql("Top_MVPs_2017", conn, if_exists="replace", index=False)

print(" ETL Completed. Results saved to SQLite database (ipl2017_etl.db)")

with pd.ExcelWriter("IPL2017_ETL_Insights.xlsx") as writer:
    top_batsmen.to_excel(writer, sheet_name="TopBatsmen", index=False)
    team_wins.to_excel(writer, sheet_name="TeamWins", index=False)
    top_mvps.to_excel(writer, sheet_name="TopMVPs", index=False)

from google.colab import files
files.download("IPL2017_ETL_Insights.xlsx")